Abc issue6 refactor
hashicorp/terraform-aws-consul-enterprise-hvd pull request #9
Opened 2024-11-06 12:08 UTC by abuxton

## Description
refactor secrets to use SSM not paramter store

## Related issue
#6 

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [x] This change requires a documentation update

## How has this been tested?
- [Describe the tests you ran to verify your changes]
- [Provide any results or outcomes from the tests]
- [Include any additional notes related to the tests]

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

## Additional notes
update to examples folder to use SSM not parameter store

2024-11-21 16:40 UTC, thejohnny approved these changes

2025-01-06 19:06 UTC, pjohnson24 submitted a review, later dismissed

2025-01-07 11:26 UTC, roooms commented
Adding @dcanadillas for review. Once he has approved this can be merged.

2025-01-09 09:41 UTC, dcanadillas approved these changes
LGTM!

2025-01-15 15:02 UTC, abuxton reviewed
lgtm

2025-01-15 16:11 UTC, pjohnson24 commented
Looks good

2025-01-15 16:11 UTC, pjohnson24 submitted a review, later dismissed

2025-01-15 16:32 UTC, jrx requested changes

2025-07-29 14:37 UTC, pjohnson24 commented
Re-approving

2025-07-29 14:38 UTC, pjohnson24 approved these changes
Looks good to me.

2025-07-29 14:40 UTC, pjohnson24 approved these changes

2025-07-29 14:42 UTC, merged